package com.fakepixel.fpu.utils;

import java.awt.Color;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.FontRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.WorldRenderer;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.entity.Entity;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.util.BlockPos;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.MathHelper;
import net.minecraft.util.ResourceLocation;
import org.lwjgl.opengl.GL11;

public class WaypointUtils {
    private static final ResourceLocation beaconBeam = new ResourceLocation("textures/entity/beacon_beam.png");

    public static void renderBeaconBeam(double x, double y, double z, int rgb, float alphaMultiplier, float partialTicks) {
        int topOffset = 0 + 300;
        Tessellator tessellator = Tessellator.getInstance();
        WorldRenderer worldrenderer = tessellator.getWorldRenderer();
        Minecraft.getMinecraft().getTextureManager().bindTexture(beaconBeam);
        GL11.glTexParameterf(3553, 10242, 10497.0f);
        GL11.glTexParameterf(3553, 10243, 10497.0f);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        GlStateManager.enableTexture2D();
        GlStateManager.tryBlendFuncSeparate(770, 1, 1, 0);
        GlStateManager.enableBlend();
        GlStateManager.tryBlendFuncSeparate(770, 771, 1, 0);
        double time = Minecraft.getMinecraft().theWorld.getTotalWorldTime() + ((double) partialTicks);
        double d1 = MathHelper.func_181162_h(((-time) * 0.2d) - ((double) MathHelper.floor_double((-time) * 0.1d)));
        float r = ((rgb >> 16) & 255) / 255.0f;
        float g = ((rgb >> 8) & 255) / 255.0f;
        float b = (rgb & 255) / 255.0f;
        double d2 = time * 0.025d * (-1.5d);
        double d4 = 0.5d + (Math.cos(d2 + 2.356194490192345d) * 0.2d);
        double d5 = 0.5d + (Math.sin(d2 + 2.356194490192345d) * 0.2d);
        double d6 = 0.5d + (Math.cos(d2 + 0.7853981633974483d) * 0.2d);
        double d7 = 0.5d + (Math.sin(d2 + 0.7853981633974483d) * 0.2d);
        double d8 = 0.5d + (Math.cos(d2 + 3.9269908169872414d) * 0.2d);
        double d9 = 0.5d + (Math.sin(d2 + 3.9269908169872414d) * 0.2d);
        double d10 = 0.5d + (Math.cos(d2 + 5.497787143782138d) * 0.2d);
        double d11 = 0.5d + (Math.sin(d2 + 5.497787143782138d) * 0.2d);
        double d14 = (-1.0d) + d1;
        double d15 = (((double) 300) * 2.5d) + d14;
        worldrenderer.begin(7, DefaultVertexFormats.POSITION_TEX_COLOR);
        worldrenderer.pos(x + d4, y + ((double) topOffset), z + d5).tex(1.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d4, y + ((double) 0), z + d5).tex(1.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d6, y + ((double) 0), z + d7).tex(0.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d6, y + ((double) topOffset), z + d7).tex(0.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d10, y + ((double) topOffset), z + d11).tex(1.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d10, y + ((double) 0), z + d11).tex(1.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d8, y + ((double) 0), z + d9).tex(0.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d8, y + ((double) topOffset), z + d9).tex(0.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d6, y + ((double) topOffset), z + d7).tex(1.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d6, y + ((double) 0), z + d7).tex(1.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d10, y + ((double) 0), z + d11).tex(0.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d10, y + ((double) topOffset), z + d11).tex(0.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d8, y + ((double) topOffset), z + d9).tex(1.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + d8, y + ((double) 0), z + d9).tex(1.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d4, y + ((double) 0), z + d5).tex(0.0d, d14).color(r, g, b, 1.0f).endVertex();
        worldrenderer.pos(x + d4, y + ((double) topOffset), z + d5).tex(0.0d, d15).color(r, g, b, 1.0f * alphaMultiplier).endVertex();
        tessellator.draw();
        GlStateManager.disableCull();
        double d12 = (-1.0d) + d1;
        double d13 = ((double) 300) + d12;
        worldrenderer.begin(7, DefaultVertexFormats.POSITION_TEX_COLOR);
        worldrenderer.pos(x + 0.2d, y + ((double) topOffset), z + 0.2d).tex(1.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) 0), z + 0.2d).tex(1.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) 0), z + 0.2d).tex(0.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) topOffset), z + 0.2d).tex(0.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) topOffset), z + 0.8d).tex(1.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) 0), z + 0.8d).tex(1.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) 0), z + 0.8d).tex(0.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) topOffset), z + 0.8d).tex(0.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) topOffset), z + 0.2d).tex(1.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) 0), z + 0.2d).tex(1.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) 0), z + 0.8d).tex(0.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.8d, y + ((double) topOffset), z + 0.8d).tex(0.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) topOffset), z + 0.8d).tex(1.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) 0), z + 0.8d).tex(1.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) 0), z + 0.2d).tex(0.0d, d12).color(r, g, b, 0.25f).endVertex();
        worldrenderer.pos(x + 0.2d, y + ((double) topOffset), z + 0.2d).tex(0.0d, d13).color(r, g, b, 0.25f * alphaMultiplier).endVertex();
        tessellator.draw();
    }

    public static void drawFilledBoundingBox(AxisAlignedBB aabb, Color c, float alphaMultiplier) {
        GlStateManager.enableBlend();
        GlStateManager.disableLighting();
        GlStateManager.tryBlendFuncSeparate(770, 771, 1, 0);
        GlStateManager.disableTexture2D();
        Tessellator tessellator = Tessellator.getInstance();
        WorldRenderer worldrenderer = tessellator.getWorldRenderer();
        GlStateManager.color(c.getRed() / 255.0f, c.getGreen() / 255.0f, c.getBlue() / 255.0f, (c.getAlpha() / 255.0f) * alphaMultiplier);
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.maxZ).endVertex();
        tessellator.draw();
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.minZ).endVertex();
        tessellator.draw();
        GlStateManager.color((c.getRed() / 255.0f) * 0.8f, (c.getGreen() / 255.0f) * 0.8f, (c.getBlue() / 255.0f) * 0.8f, (c.getAlpha() / 255.0f) * alphaMultiplier);
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.minZ).endVertex();
        tessellator.draw();
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.maxZ).endVertex();
        tessellator.draw();
        GlStateManager.color((c.getRed() / 255.0f) * 0.9f, (c.getGreen() / 255.0f) * 0.9f, (c.getBlue() / 255.0f) * 0.9f, (c.getAlpha() / 255.0f) * alphaMultiplier);
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.minZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.minZ).endVertex();
        tessellator.draw();
        worldrenderer.begin(7, DefaultVertexFormats.POSITION);
        worldrenderer.pos(aabb.minX, aabb.minY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.minY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.maxX, aabb.maxY, aabb.maxZ).endVertex();
        worldrenderer.pos(aabb.minX, aabb.maxY, aabb.maxZ).endVertex();
        tessellator.draw();
        GlStateManager.enableTexture2D();
        GlStateManager.disableBlend();
    }

    public static void renderWaypointText(String str, BlockPos loc, float partialTicks) {
        GlStateManager.alphaFunc(516, 0.1f);
        GlStateManager.pushMatrix();
        Entity viewer = Minecraft.getMinecraft().getRenderViewEntity();
        double viewerX = viewer.lastTickPosX + ((viewer.posX - viewer.lastTickPosX) * ((double) partialTicks));
        double viewerY = viewer.lastTickPosY + ((viewer.posY - viewer.lastTickPosY) * ((double) partialTicks));
        double viewerZ = viewer.lastTickPosZ + ((viewer.posZ - viewer.lastTickPosZ) * ((double) partialTicks));
        double x = ((double) loc.getX()) - viewerX;
        double y = (((double) loc.getY()) - viewerY) - ((double) viewer.getEyeHeight());
        double z = ((double) loc.getZ()) - viewerZ;
        double distSq = (x * x) + (y * y) + (z * z);
        double dist = Math.sqrt(distSq);
        if (distSq > 144.0d) {
            x *= 12.0d / dist;
            y *= 12.0d / dist;
            z *= 12.0d / dist;
        }
        GlStateManager.translate(x, y, z);
        GlStateManager.translate(0.0f, viewer.getEyeHeight(), 0.0f);
        drawNametag(str);
        GlStateManager.rotate(-Minecraft.getMinecraft().getRenderManager().playerViewY, 0.0f, 1.0f, 0.0f);
        GlStateManager.rotate(Minecraft.getMinecraft().getRenderManager().playerViewX, 1.0f, 0.0f, 0.0f);
        GlStateManager.translate(0.0f, -0.25f, 0.0f);
        GlStateManager.rotate(-Minecraft.getMinecraft().getRenderManager().playerViewX, 1.0f, 0.0f, 0.0f);
        GlStateManager.rotate(Minecraft.getMinecraft().getRenderManager().playerViewY, 0.0f, 1.0f, 0.0f);
        drawNametag(EnumChatFormatting.YELLOW.toString() + Math.round(dist) + "m");
        GlStateManager.popMatrix();
        GlStateManager.disableLighting();
    }

    public static void drawNametag(String str) {
        FontRenderer fontrenderer = Minecraft.getMinecraft().fontRendererObj;
        float f1 = 0.016666668f * 1.6f;
        GlStateManager.pushMatrix();
        GL11.glNormal3f(0.0f, 1.0f, 0.0f);
        GlStateManager.rotate(-Minecraft.getMinecraft().getRenderManager().playerViewY, 0.0f, 1.0f, 0.0f);
        GlStateManager.rotate(Minecraft.getMinecraft().getRenderManager().playerViewX, 1.0f, 0.0f, 0.0f);
        GlStateManager.scale(-f1, -f1, f1);
        GlStateManager.disableLighting();
        GlStateManager.depthMask(false);
        GlStateManager.disableDepth();
        GlStateManager.enableBlend();
        GlStateManager.tryBlendFuncSeparate(770, 771, 1, 0);
        Tessellator tessellator = Tessellator.getInstance();
        WorldRenderer worldrenderer = tessellator.getWorldRenderer();
        int j = fontrenderer.getStringWidth(str) / 2;
        GlStateManager.disableTexture2D();
        worldrenderer.begin(7, DefaultVertexFormats.POSITION_COLOR);
        worldrenderer.pos((-j) - 1, (-1) + 0, 0.0d).color(0.0f, 0.0f, 0.0f, 0.25f).endVertex();
        worldrenderer.pos((-j) - 1, 8 + 0, 0.0d).color(0.0f, 0.0f, 0.0f, 0.25f).endVertex();
        worldrenderer.pos(j + 1, 8 + 0, 0.0d).color(0.0f, 0.0f, 0.0f, 0.25f).endVertex();
        worldrenderer.pos(j + 1, (-1) + 0, 0.0d).color(0.0f, 0.0f, 0.0f, 0.25f).endVertex();
        tessellator.draw();
        GlStateManager.enableTexture2D();
        fontrenderer.drawString(str, (-fontrenderer.getStringWidth(str)) / 2, 0, 553648127);
        GlStateManager.depthMask(true);
        fontrenderer.drawString(str, (-fontrenderer.getStringWidth(str)) / 2, 0, -1);
        GlStateManager.enableDepth();
        GlStateManager.enableBlend();
        GlStateManager.color(1.0f, 1.0f, 1.0f, 1.0f);
        GlStateManager.popMatrix();
    }
}
